main: me.Verveine.LGUHC.Main
name: VervUHC
version: 0.1
author: Verveine

commands:
   alg:
      description: Commandes admin VervUHC
      usage: /alg
   lg:
      description: Commandes joueur VervUHC
      usage: /lg